### ISSUE TITLE
Filtering by Baseline status

### ISSUE THREAD

**Issue by foolip** [Shinigami92/baseline-green#1]
It would be very cool if https://shinigami92.github.io/baseline-green/ could be filtered by Baseline status, and the filter I'm after is low+high, filtering out the features that aren't Baseline yet.

I tried typing into the search box, but the text is white on white, and also it seems to only filter on the feature ID.

FYI, there's now a `name` field for every feature, which will be nicer to display. Just make sure to escape it properly, it contains all kinds of markup :)

**Comment by Shinigami92** [comment]
Your wish is my command 🫡

Potential around weekend 😇

**Comment by Shinigami92** [comment]
@foolip filter added in https://github.com/Shinigami92/baseline-green/commit/2e37e85429e3ec20024f254f73620b8214e03f84

Please make sure to clear your cache with `Ctrl + Shift + R`

I know it is not fancy ^^ but it works for now. So let me know how I can improve further.

Also the search field... it searches in every baseline entry on `JSON.stringify` :laughing:  
https://github.com/Shinigami92/baseline-green/blob/2e37e85429e3ec20024f254f73620b8214e03f84/src/App.vue#L74-L78
It is REALLY basic

**Comment by foolip** [comment]
Thank you @Shinigami92, that's great! I see you've also used the `name` field now.

My next feature request would be persisting the search and select box state in the URL, by appending something like `#baseline=low,high&q=css` to list Baseline CSS features. I've found that using https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams is great for creating and parsing such URLs on the client side.

Also feel free to ignore my requests and just do what you think is fun, I presume this is a hobby project :)

**Comment by Shinigami92** [comment]
I absolutely love your proposals.
It is much more valuable for me to work for someone else that request real wishes as of trying around and do stuff for only myself or no one at the end 🙂 

I can use e.g. https://vueuse.org/core/useUrlSearchParams/ for this 👍 

This request will make the webside also much more shareable due to having the filters in the link itself 🚀 

_Reminder for myself_: now I really need to use `'false'` and `'undefined'` instead of `false` and `undefined` for the `filterBaselineStatus` 😅 

The only one thing is that I need to find dedicated time, but I really enjoy now what I'm doing here, it is just that I have so many fun stuff 🙂 
So not sure if I can work on this before next week 🥲

**Comment by foolip** [comment]
@Shinigami92 if you can make the time for URL filtering that'll be very cool, and there's no hurry at all.

**Comment by Shinigami92** [comment]
> @Shinigami92 if you can make the time for URL filtering that'll be very cool, and there's no hurry at all.

UrlSearchParams added :smiley: 

I will close this issue for now. Please use new dedicated issues for every new request. Keep them coming :slightly_smiling_face:
